GPP=x86_64-apple-darwin18-clang++
CXXFLAGS=-O3 -DNDEBUG `wx-config --cppflags` -DWX3 -Wno-invalid-source-encoding
LDFLAGS=`wx-config --libs std,stc,aui`
OBJS_DIR=../temp/zinjai/release.mac

all: ../zinjai.mac

include Makefile.common

clean:
	rm -rf ${OBJS} ../zinjai

../zinjai.mac: ${OBJS_DIR} ${OBJS}
	${GPP} ${OBJS} ${LDFLAGS} -o $@

${OBJS_DIR}:
	mkdir -p ${OBJS_DIR}

